<?php

/**
 * @var \Vnext\BasicTraining\Block\Details $block
 */
$viewModel = $block->getViewModel();
$postArray = $viewModel->getDetails();

//echo ($postArray->getName());
//echo ($postArray->getdob()->getDate());
?>

<?php $gridrecords = $block->getDetails();
//echo $gridrecords->getDate();
?>
<div class="table-wrapper orders-history">
    <a href="<?php echo $block->getUrl('student/post/index') ?>"> Home</a>

    <!--        Tabel-->
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('Entity Id') ?></th>
            <th scope="col" class="col title"><?php echo __('Name') ?></th>
            <th scope="col" class="col product"><?php echo __('Gender') ?></th>
            <th scope="col" class="col amount"><?php echo __('Dob') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('Entity Id')) ?>" class="col id">
                <?php echo $gridrecords->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col id">
                <?php echo $gridrecords->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Gender')) ?>" class="col id">
                <?php if ($gridrecords->getGender() == 1) {
                    echo "Nam";
                } else {
                    echo "Nữ";
                } ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Dob')) ?>" class="col id">
                <?php echo $gridrecords->getDob() ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>

